sudo: required
dist: trusty
language: cpp
compiler: g++

install: export CXX="g++-7"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

notifications:
 email:
  on_success: never
  on_failure: always

before_install: sudo apt-get update -qq

script: make --directory EverythingLibs
